services:
  web:
    image: nginx:latest
    labels:
      sablier.enable: "true"
      sablier.group: "web"
    networks:
      - net
  caddy:
    build:
      context: .
      dockerfile: Caddy-Dockerfile
    ports:
      - "8080:80"
    networks:
      - net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  net:
    driver: bridge
